CoursesWebsite/Controllers/CourseController.cs
using AutoMapper;
using CoursesWebsite.App_Start;
using CoursesWebsite.Models;
using CoursesWebsite.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CoursesWebsite.Controllers
{
    public class CourseController : Controller
    {

        private readonly IMapper mapper;
        private readonly CourseService courseService;

        public CourseController()
        {

            courseService = new CourseService();

            mapper = AutoMapperConfig.Mapper;
        }
        // GET: Course
        public ActionResult Index()
        {
            var Courses = courseService.ReadByALL();
            var mappedCourse = mapper.Map<List<CourseModel>>(Courses);
            return View(mappedCourse);
        }
        public ActionResult Info(int?id)
        {
            if(id==null||id==0)
            {
                return HttpNotFound("This Course Is Not Found");
            }
            var MyCourse = courseService.ReadBYID(id.Value);
            if(MyCourse==null)
            {
                return HttpNotFound("This Course Is Not Found");

            }
            var mappedcourse = mapper.Map<CourseModel>(MyCourse);
            return View(mappedcourse);
        }
        public ActionResult Subscribe(int id)
        {
            if(!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account", new { ReturnUrl = $"/Course/Subscribe/{id}" });
            }
            return View();
        }
    }  
}

CoursesWebsite/Controllers/DefaultController.cs
using AutoMapper;
using CoursesWebsite.App_Start;
using CoursesWebsite.Models;
using CoursesWebsite.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CoursesWebsite.Controllers
{
    public class DefaultController : Controller
    {
        private readonly IMapper mapper;
        private readonly CourseService courseService;
    
        public DefaultController()
        {

            courseService = new CourseService();
        
            mapper = AutoMapperConfig.Mapper;
        }
        // GET: Default
        public ActionResult Index()
        {
            var Courses = courseService.ReadByALL();
            var mappedCourse = mapper.Map<List<CourseModel>>(Courses);
            return View(mappedCourse);
        }
    }
}

CoursesWebsite/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

CoursesWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>My Courses-@ViewBag.Title</title>
    <!-- Favicon-->
    <link rel="shorticon" type="image/x-icon" href="~/assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />
    

    @*  *@
       <link href="~/Scripts/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
</head>
<body>

    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container px-lg-5">
            <a class="navbar-brand" href="@Url.Action("Index","Default")">My Courses</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="@Url.Action("Index","Default")">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("Index","Course")">Courses</a></li>
                    @Html.Partial("_LoginPartial")
                </ul>
            </div>
        </div>
    </nav>
    <!-- Header-->
    <header class="py-5">
        <div class="container px-lg-5">
            <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
                <div class="m-4 m-lg-5">
                    <h1 class="display-5 fw-bold">A warm welcome!</h1>
                    <p class="fs-4">Bootstrap utility classes are used to create this jumbotron since the old component has been removed from the framework. Why create custom CSS when you can use utilities?</p>
                    <a class="btn btn-primary btn-lg" href="#!">Call to action</a>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        @RenderBody()
    </div>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; My Courses @DateTime.Now.Year</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.5.2/bootbox.min.js"></script>
    
    @*  *@
    <script src="~/Scripts/jquery.min.js"></script>
    @*<script src="~/Scripts/bootstrap.bundle.js"></script>*@

    <!-- Core plugin JavaScript-->
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.5.2/bootbox.min.js"></script>
</body>
</html>

CoursesWebsite/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title</title>
    <!-- Favicon-->
    <link rel="shorticon" type="image/x-icon" href="~/assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />
    <link href="~/css/User-Style.css" rel="stylesheet" />

</head>
<body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container px-lg-5">
            <a class="navbar-brand" href="#!">My Courses</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div >
    @RenderBody()
    </div>
    <!-- Footer-->
    
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/js/scripts.js"></script>
</body>
</html>

CoursesWebsite/Views/Shared/_ViewListCourses.cshtml
@model IEnumerable<CoursesWebsite.Models.CourseModel>
<div class="row text-center">

    @foreach (var courseItem in Model)
    {
<div class="col-lg-3 col-md-6 mb-4">
    <div class="card h-100">
        <img class="card-img-top" src="~/Uploads/Courses/@courseItem.Image_ID" alt="">
        <div class="card-body">
            <h4 class="card-title">@courseItem.Name</h4>
            <p class="card-text">
                @courseItem.Desciption
            </p>
        </div>
        <div class="card-footer">
            <a href="@Url.Action("Info", "Course", new {id = courseItem.ID })" class="btn btn-primary">Find Out More!</a>
        </div>
    </div>
</div>}


</div>