CoursesWebsite/Areas/Admin/Controllers/CourseController.cs
using AutoMapper;
using CoursesWebsite.App_Start;
using CoursesWebsite.Data;
using CoursesWebsite.Models;
using CoursesWebsite.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CoursesWebsite.Areas.Admin.Controllers
{
    [Authorize (Roles ="Admin")]
    public class CourseController : Controller
    {
        private readonly IMapper mapper;
        private readonly CourseService courseService;
        private readonly CategoryService categoryService;
        private readonly TrainerService trainerService;
        public CourseController()
        {

            courseService = new CourseService();
            categoryService = new CategoryService();
            trainerService = new TrainerService();
            mapper = AutoMapperConfig.Mapper;
        }
        // GET: Admin/Course
        public ActionResult Index(string Query= null, int? CategoryId = null ,int?TrainerId=null)
        {
            var CourseListModel = new CourseListModel();
            InitSelectList(ref CourseListModel);
            var courses = courseService.ReadByALL(Query,CategoryId,TrainerId);
            var mappedcourses = mapper.Map < IEnumerable< CourseModel >> (courses);
            CourseListModel.Courses = mappedcourses;
            return View(CourseListModel);
        }
        public ActionResult Create()
        {
            var CourseModel = new CourseModel();
            InitSelectList(ref CourseModel);
            return View(CourseModel);
        }
        [HttpPost]
        public ActionResult Create(CourseModel CourseData)
        {
            InitSelectList(ref CourseData);

            //if (CourseData.ImageFile==null||CourseData.ImageFile.ContentLength==0)
            //{
            //    return View(CourseData);
            //}
         
            try
            {
                if (ModelState.IsValid)
                {
                    CourseData.Image_ID = SaveImageFile(CourseData.ImageFile);

                    var mappedCourse = mapper.Map<Course>(CourseData);
                    mappedCourse.Category = null;
                    mappedCourse.Trainer = null;
                    int result = courseService.Create(mappedCourse);
                    if (result >= 1)
                    {
                        return RedirectToAction("Index");
                    }
                    ViewBag.Message = "An Error Occured";
                }
                return View(CourseData);
            }
            catch(Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(CourseData);
            }
            
        }
        public ActionResult Edit(int? Id)
        {
            if(Id==null)
            {
                return HttpNotFound();
            }
            
            var currentCoursedata = courseService.ReadBYID(Id.Value);
            var mappedcourse = mapper.Map<CourseModel>(currentCoursedata);
            InitSelectList(ref mappedcourse);
            return View(mappedcourse);
        }
        [HttpPost]
        public ActionResult Edit(CourseModel CourseData)
        {
            InitSelectList(ref CourseData);

            try
            {
                if (ModelState.IsValid)
                {
                    CourseData.Image_ID=SaveImageFile(CourseData.ImageFile, CourseData.Image_ID);

                    var mappedCourse = mapper.Map<Course>(CourseData);
                    mappedCourse.Category = null;
                    mappedCourse.Trainer = null;

                    int result = courseService.Update(mappedCourse);
                     
                    if (result >= 1)
                    {
                        return RedirectToAction("Index");
                    }
                    ViewBag.Message = "An Error Occured";
                }
                return View(CourseData);
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(CourseData);
            }

        }
        private void InitSelectList(ref CourseModel courseModel)
        {
            var mappedCategory = GetCategories();
            courseModel.Categories = new SelectList(mappedCategory, "Id", "Name");

            var mappedTrainer = GetTrainers();
            courseModel.Trainers = new SelectList(mappedTrainer, "ID", "Name");
        }

        private void InitSelectList(ref CourseListModel  courseList)
        {
           var mappedCategory= GetCategories();
            courseList.Categories = new SelectList(mappedCategory, "Id", "Name");

            var mappedTrainer = GetTrainers();
            courseList.Trainers = new SelectList(mappedTrainer, "ID", "Name");
        }

        private IEnumerable<CategoryModel>GetCategories()
        {
            var Categories = categoryService.ReadAll();
            var mappedCategory = mapper.Map<IEnumerable<CategoryModel>>(Categories);
            return mappedCategory;
        }
        private IEnumerable<TrainerModel> GetTrainers()
        {
            var Trainers = trainerService.ReadALL();
            var mappedTrainer = mapper.Map<IEnumerable<TrainerModel>>(Trainers);
            return mappedTrainer;
        }

        private string SaveImageFile(HttpPostedFileBase ImageFile,string CurrentImageID="")
        {
            if (ImageFile != null)
            {
                var FileExtension = Path.GetExtension(ImageFile.FileName);
                var imageGuid = Guid.NewGuid().ToString();
                string Image_ID = imageGuid + FileExtension;

                //saving file or picture
                string FilePath = Server.MapPath($"~/Uploads/Courses/{Image_ID}");
                ImageFile.SaveAs(FilePath);

                //Delete Old File
                if (!string.IsNullOrEmpty(CurrentImageID))
                {
                    string OldFilePath = Server.MapPath($"~/Uploads/Courses/{CurrentImageID}");
                    System.IO.File.Delete(OldFilePath);
                }
                return Image_ID;

            }
            return CurrentImageID;
        }
    }
}

CoursesWebsite/Areas/Admin/Controllers/CourseUnitsController.cs
using AutoMapper;
using CoursesWebsite.App_Start;
using CoursesWebsite.Data;
using CoursesWebsite.Models;
using CoursesWebsite.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CoursesWebsite.Areas.Admin.Controllers
{
    public class CourseUnitsController : Controller
    {
        private readonly IMapper mapper;
        private readonly CourseUnitService courseUnitService;

        public CourseUnitsController()
        {
            courseUnitService = new CourseUnitService();
            mapper = AutoMapperConfig.Mapper;

        }
        // GET: Admin/CourseUnits?CourseId
        public ActionResult Index(int? courseId)
        {
            if(courseId == null)
            {
                return HttpNotFound();
            }
            var unit= courseUnitService.ReadByALL(courseId.Value);
            var mappedUnits = mapper.Map<IEnumerable<CourseUnitModel>>(unit);
            ViewBag.CourseName = mappedUnits.FirstOrDefault()?.Name;
            ViewBag.CourseId = courseId;
            return View(mappedUnits);
        }

        // GET: Admin/CourseUnits/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/CourseUnits/Create
        public ActionResult Create()
        {
            return View();
        }
        // create /postديه طريقة اقدر اعملها فى 
        //ابعتهم ك parameters
        //public JsonResult Create(int CourseId,string UnitName)
        //{
        //    var unit = new Course_Units
        //    {
        //        Name=UnitName,
        //        Course_Id=CourseId
              
        //    };
        //    return Json();
        //}
        //واقدر اعملها بطريقة تانية زى انى ابعتله 
        //object بدل من
        //string name / int course id as parameter عملت

        // POST: Admin/CourseUnits/Create
        [HttpPost]
        public ActionResult Create(CourseUnitModel unitdata)
        {
            
            try
            {
                // TODO: Add insert logic here

                var unit = mapper.Map<Course_Units>(unitdata);
                unit.Course = null;
                var SavingUnit = courseUnitService.Create(unit);
                //if (SavingUnit > 0)
                //{
                //    return Json(new { saved = true });
                //}
                //else if (SavingUnit == -2)
                //{
                //    return Json(new { saved = false, message = "Exists" });

                //}
                //if (SavingUnit >= 1)
                //{
                //    return RedirectToAction("Index");
                //}
                //else if (SavingUnit == -2)
                //{
                //    ViewBag.Message = "An exists Trainer with this email";

                //}
                //else
                //{
                //    ViewBag.Message = "An error Occured";

                //}
                //return View(unitdata);
                if (SavingUnit == SavingStatus.Saved)
                {
                    return Json(new { saved = true });
                }
                else if (SavingUnit == SavingStatus.Exists)
                {
                    return Json(new { saved = false, message = "Exists" });

                }
                else
                {
                    return Json(new { saved = false });
                }
            }
            catch(Exception ex)
            {
                return Json(new { saved = false, message = ex.Message });
            }
        }

        // GET: Admin/CourseUnits/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/CourseUnits/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/CourseUnits/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/CourseUnits/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CoursesWebsite/Areas/Admin/Controllers/TraineeController.cs
using AutoMapper;
using CoursesWebsite.App_Start;
using CoursesWebsite.Models;
using CoursesWebsite.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CoursesWebsite.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]

    public class TraineeController : Controller
    {
        private readonly TraineeCoursesService traineeCoursesService;
        private readonly IMapper mapper;
        public TraineeController()
        {
            traineeCoursesService = new TraineeCoursesService();
            mapper = AutoMapperConfig.Mapper;
        }
        // GET: Admin/Trainee
        public ActionResult Index(int?courseid)
        {
           if(courseid==null)
            {
                return HttpNotFound();
            }
            var TraineeCoursesList = traineeCoursesService.GetTrainees(courseid.Value);
            var MappedTraineeCourses = mapper.Map<IEnumerable<TraineeCourseModel>>(TraineeCoursesList);
            return View(MappedTraineeCourses);
        }
    }
}

CoursesWebsite/Controllers/CourseController.cs
using AutoMapper;
using CoursesWebsite.App_Start;
using CoursesWebsite.Models;
using CoursesWebsite.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CoursesWebsite.Controllers
{
    public class CourseController : Controller
    {

        private readonly IMapper mapper;
        private readonly CourseService courseService;

        public CourseController()
        {

            courseService = new CourseService();

            mapper = AutoMapperConfig.Mapper;
        }
        // GET: Course
        public ActionResult Index()
        {
            var Courses = courseService.ReadByALL();
            var mappedCourse = mapper.Map<List<CourseModel>>(Courses);
            return View(mappedCourse);
        }
        public ActionResult Info(int?id)
        {
            if(id==null||id==0)
            {
                return HttpNotFound("This Course Is Not Found");
            }
            var MyCourse = courseService.ReadBYID(id.Value);
            if(MyCourse==null)
            {
                return HttpNotFound("This Course Is Not Found");

            }
            var mappedcourse = mapper.Map<CourseModel>(MyCourse);
            return View(mappedcourse);
        }
        public ActionResult Subscribe(int id)
        {
            if(!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account", new { ReturnUrl = $"/Course/Subscribe/{id}" });
            }
            return View();
        }
    }  
}

CoursesWebsite/Areas/Admin/Views/Course/Create.cshtml
@model CoursesWebsite.Models.CourseModel

@{
    ViewBag.Title = "Add Course";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Add Course</h2>

@using (Html.BeginForm("Create","Course",FormMethod.Post,new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Trainer_ID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Trainer_ID, Model.Trainers, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Trainer_ID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Category_ID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Category_ID, Model.Categories, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Category_ID, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Desciption, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Desciption, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Desciption, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Image_ID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
           <input type="file"name="ImageFile"value="ImageFile" /> 
         
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CoursesWebsite/Areas/Admin/Views/Course/Edit.cshtml
@model CoursesWebsite.Models.CourseModel

@{
    ViewBag.Title = "Edit Course";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Edit Course</h2>

@using (Html.BeginForm("Edit", "Course",FormMethod.Post,new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.Image_ID)
    @Html.HiddenFor(model => model.ID)
    @Html.HiddenFor(model => model.Creation_Date)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Trainer_ID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Trainer_ID, Model.Trainers, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Trainer_ID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Category_ID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Category_ID, Model.Categories, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Category_ID, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Desciption, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Desciption, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Desciption, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Image_ID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile" value="ImageFile" />

        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save Changes" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CoursesWebsite/Areas/Admin/Views/Course/Index.cshtml
@model CoursesWebsite.Models.CourseListModel

@{
    ViewBag.Title = "Courses";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Courses</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "Course", FormMethod.Get, new { @class = "form-inline" }))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Query)
        @Html.TextBoxFor(m => m.Query, new { @class = "form-Control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.TrainerId)
        @Html.DropDownListFor(m => m.TrainerId, Model.Trainers, "---Select Trainer---", new { @class = "form-Control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CategoryId)
        @Html.DropDownListFor(m => m.CategoryId, Model.Categories, "---Select Category---", new { @class = "form-Control" })
    </div>
    <input type="submit" value="Search" class="btn btn-primary" />
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Courses.First().Image_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Courses.First().Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Courses.First().Creation_Date)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.Category_Id)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Courses.First().Category_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Courses.First().Trainer_Name)
        </th>
        <th>
            Trainees
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Courses)
    {
        <tr>
            <td>
                <img src="~/Uploads/Courses/@item.Image_ID" style="width:75px;" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Creation_Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Trainer_Name)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.Category_Id)
                </td>*@
            <td>
                @Html.ActionLink("Trainees", "Index", "Trainee", new { courseid = item.ID },
                               new { @class = "btn btn-primary" })
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Contents", "Index","CourseUnits", new { CourseId = item.ID }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>